services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: /home/fli/inception/srcs/.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
      # - ./website-files:/var/www/html/static
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: /home/fli/inception/srcs/.env
    ports:
      - "443:443"
    restart: unless-stopped
  
  redis:
    container_name: redis
    networks:
      - inception
    build:
      context: requirements/redis
      dockerfile: "Dockerfile"
    env_file: /home/fli/inception/srcs/.env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    env_file: /home/fli/inception/srcs/.env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    expose: 
      - "9000"
  
  ftp:
    container_name: ftp
    env_file: /home/fli/inception/srcs/.env
    volumes:
      - wordpress:/web_data
    networks:
      - inception
    build:
      context: requirements/ftp
      dockerfile: Dockerfile
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
    ports:
      - "20:20"
      - "21:21"
      - "30000-30100:30000-30100"

  # static:
  #   container_name: static
  #   networks:
  #     - inception
  #   build:
  #     context: requirements/static
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./requirements/static/website-files:/usr/share/caddy
  #     - ./requirements/static/Caddyfile:/etc/caddy/Caddyfile 
  # static:
  #   networks:
  #     - inception
  #   build:
  #     context: requirements/static
  #     dockerfile: "Dockerfile"
  #   image: static
  #   pull_policy: never
  #   volumes:
  #     - wordpress:/var/www/html
  #   restart: on-failure:2

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fli/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/fli/data/mariadb'

networks:
  inception:
    name: inception
    driver: bridge