FROM debian:bullseye

RUN apt update \
    apt install vim -y \
    apt install curl -y \
    apt install nginx -y

RUN mkdir -p /etc/nginx/ssl

RUN apt install OpenSSL -y

# COPY

# EXPOSE

# ENTRYPOINT 